# fly.toml app configuration file generated for xfiber on 2023-07-23T22:40:08+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xfiber"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
